import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'am' | 'gez';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.users': 'Manage Users',
    'nav.assets': 'Manage Assets',
    'nav.posts': 'Post News',
    'nav.profile': 'Update Profile',
    'nav.whatsNew': "What's New",
    'nav.addUser': 'Add New User',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.welcome': 'Welcome to Sunday School Portal',
    'auth.logout': 'Logout',
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.role': 'Role',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'profile.title': 'Update Profile',
    'profile.personal': 'Personal Information',
    'profile.details': 'Location & Background',
    'profile.account': 'Change Password',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.phone': 'Phone',
    'profile.aboutMe': 'About Me',
    'profile.address': 'Address',
    'profile.city': 'City',
    'profile.country': 'Country',
    'profile.occupation': 'Occupation',
    'profile.education': 'Education',
    'profile.sundaySchool': 'Sunday School',
    'profile.responsibility': 'Responsibility',
    'profile.avatar': 'Profile Picture',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'dashboard.overview': 'Overview of your Sunday School management system',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.totalAssets': 'Total Assets',
    'dashboard.activePosts': 'Active Posts',
    'dashboard.engagement': 'Engagement Rate',
    'dashboard.recentActivity': 'Recent Activity',
    'users.manage': 'Manage Users',
    'users.viewManage': 'View and manage all registered users',
    'users.searchPlaceholder': 'Search users...',
    'users.user': 'User',
    'users.viewDetails': 'View Details',
    'assets.manage': 'Manage Assets',
    'assets.overview': 'Track and manage all church assets',
    'assets.addNew': 'Register New Asset',
    'assets.code': 'Asset Code',
    'assets.name': 'Name',
    'assets.category': 'Category',
    'assets.assignedTo': 'Assigned To',
    'assets.purchaseDate': 'Purchase Date',
    'posts.manage': 'Post News',
    'posts.overview': 'Create and manage news posts',
    'posts.createNew': 'Create New Post',
    'posts.title': 'Title',
    'posts.content': 'Content',
    'posts.author': 'Author',
    'posts.date': 'Date',
  },
  am: {
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.users': 'ተጠቃሚዎችን ያስተዳድሩ',
    'nav.assets': 'ንብረቶችን ያስተዳድሩ',
    'nav.posts': 'ዜና ያስተዳድሩ',
    'nav.profile': 'መገለጫ አዘምን',
    'nav.whatsNew': 'አዲስ ምንድን ነው',
    'nav.addUser': 'አዲስ ተጠቃሚ ያክሉ',
    'auth.login': 'ግባ',
    'auth.signup': 'ተመዝገብ',
    'auth.email': 'ኢሜይል',
    'auth.password': 'የይለፍ ቃል',
    'auth.welcome': 'ወደ የእሁድ ትምህርት ቤት ፖርታል እንኳን በደህና መጡ',
    'auth.logout': 'ውጣ',
    'common.save': 'ለውጦችን አስቀምጥ',
    'common.cancel': 'ሰርዝ',
    'common.delete': 'አጥፋ',
    'common.edit': 'አርትዕ',
    'common.search': 'ፈልግ',
    'common.actions': 'እርምጃዎች',
    'common.status': 'ሁኔታ',
    'common.role': 'ሚና',
    'common.active': 'ንቁ',
    'common.inactive': 'ንቁ ያልሆነ',
    'profile.title': 'መገለጫ አዘምን',
    'profile.personal': 'የግል መረጃ',
    'profile.details': 'አድራሻ እና ዳራ',
    'profile.account': 'የይለፍ ቃል ቀይር',
    'profile.firstName': 'ስም',
    'profile.lastName': 'የአባት ስም',
    'profile.phone': 'ስልክ',
    'profile.aboutMe': 'ስለ እኔ',
    'profile.address': 'አድራሻ',
    'profile.city': 'ከተማ',
    'profile.country': 'ሀገር',
    'profile.occupation': 'ስራ',
    'profile.education': 'ትምህርት',
    'profile.sundaySchool': 'የእሁድ ትምህርት ቤት',
    'profile.responsibility': 'ኃላፊነት',
    'profile.avatar': 'የመገለጫ ምስል',
    'profile.currentPassword': 'የአሁኑ የይለፍ ቃል',
    'profile.newPassword': 'አዲስ የይለፍ ቃል',
    'profile.confirmPassword': 'አዲስ የይለፍ ቃል ያረጋግጡ',
    'dashboard.overview': 'የእሁድ ትምህርት ቤት አስተዳደር ስርዓት አጠቃላይ እይታ',
    'dashboard.totalUsers': 'ጠቅላላ ተጠቃሚዎች',
    'dashboard.totalAssets': 'ጠቅላላ ንብረቶች',
    'dashboard.activePosts': 'ንቁ መልዕክቶች',
    'dashboard.engagement': 'የተሳትፎ መጠን',
    'dashboard.recentActivity': 'የቅርብ ጊዜ እንቅስቃሴ',
    'users.manage': 'ተጠቃሚዎችን ያስተዳድሩ',
    'users.viewManage': 'ሁሉንም የተመዘገቡ ተጠቃሚዎችን ይመልከቱ እና ያስተዳድሩ',
    'users.searchPlaceholder': 'ተጠቃሚዎችን ፈልግ...',
    'users.user': 'ተጠቃሚ',
    'users.viewDetails': 'ዝርዝሮችን ይመልከቱ',
    'assets.manage': 'ንብረቶችን ያስተዳድሩ',
    'assets.overview': 'ሁሉንም የቤተክርስቲያን ንብረቶች ይከታተሉ እና ያስተዳድሩ',
    'assets.addNew': 'አዲስ ንብረት ይመዝግቡ',
    'assets.code': 'የንብረት ኮድ',
    'assets.name': 'ስም',
    'assets.category': 'ምድብ',
    'assets.assignedTo': 'የተመደበለት',
    'assets.purchaseDate': 'የግዢ ቀን',
    'posts.manage': 'ዜና ያስተዳድሩ',
    'posts.overview': 'የዜና መልዕክቶችን ይፍጠሩ እና ያስተዳድሩ',
    'posts.createNew': 'አዲስ መልዕክት ይፍጠሩ',
    'posts.title': 'ርዕስ',
    'posts.content': 'ይዘት',
    'posts.author': 'ደራሲ',
    'posts.date': 'ቀን',
  },
  gez: {
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.users': 'ተጠቃሚዎችን ያስተዳድሩ',
    'nav.assets': 'ንብረቶችን ያስተዳድሩ',
    'nav.posts': 'ዜና ያስተዳድሩ',
    'nav.profile': 'መገለጫ አዘምን',
    'nav.whatsNew': 'አዲስ ምንድን ነው',
    'nav.addUser': 'አዲስ ተጠቃሚ ያክሉ',
    'auth.login': 'ግባ',
    'auth.signup': 'ተመዝገብ',
    'auth.email': 'ኢሜይል',
    'auth.password': 'የይለፍ ቃል',
    'auth.welcome': 'ወደ የእሁድ ትምህርት ቤት ፖርታል እንኳን በደህና መጡ',
    'auth.logout': 'ውጣ',
    'common.save': 'ለውጦችን አስቀምጥ',
    'common.cancel': 'ሰርዝ',
    'common.delete': 'አጥፋ',
    'common.edit': 'አርትዕ',
    'common.search': 'ፈልግ',
    'common.actions': 'እርምጃዎች',
    'common.status': 'ሁኔታ',
    'common.role': 'ሚና',
    'common.active': 'ንቁ',
    'common.inactive': 'ንቁ ያልሆነ',
    'profile.title': 'መገለጫ አዘምን',
    'profile.personal': 'የግል መረጃ',
    'profile.details': 'አድራሻ እና ዳራ',
    'profile.account': 'የይለፍ ቃል ቀይር',
    'profile.firstName': 'ስም',
    'profile.lastName': 'የአባት ስም',
    'profile.phone': 'ስልክ',
    'profile.aboutMe': 'ስለ እኔ',
    'profile.address': 'አድራሻ',
    'profile.city': 'ከተማ',
    'profile.country': 'ሀገር',
    'profile.occupation': 'ስራ',
    'profile.education': 'ትምህርት',
    'profile.sundaySchool': 'የእሁድ ትምህርት ቤት',
    'profile.responsibility': 'ኃላፊነት',
    'profile.avatar': 'የመገለጫ ምስል',
    'profile.currentPassword': 'የአሁኑ የይለፍ ቃል',
    'profile.newPassword': 'አዲስ የይለፍ ቃል',
    'profile.confirmPassword': 'አዲስ የይለፍ ቃል ያረጋግጡ',
    'dashboard.overview': 'የእሁድ ትምህርት ቤት አስተዳደር ስርዓት አጠቃላይ እይታ',
    'dashboard.totalUsers': 'ጠቅላላ ተጠቃሚዎች',
    'dashboard.totalAssets': 'ጠቅላላ ንብረቶች',
    'dashboard.activePosts': 'ንቁ መልዕክቶች',
    'dashboard.engagement': 'የተሳትፎ መጠን',
    'dashboard.recentActivity': 'የቅርብ ጊዜ እንቅስቃሴ',
    'users.manage': 'ተጠቃሚዎችን ያስተዳድሩ',
    'users.viewManage': 'ሁሉንም የተመዘገቡ ተጠቃሚዎችን ይመልከቱ እና ያስተዳድሩ',
    'users.searchPlaceholder': 'ተጠቃሚዎችን ፈልግ...',
    'users.user': 'ተጠቃሚ',
    'users.viewDetails': 'ዝርዝሮችን ይመልከቱ',
    'assets.manage': 'ንብረቶችን ያስተዳድሩ',
    'assets.overview': 'ሁሉንም የቤተክርስቲያን ንብረቶች ይከታተሉ እና ያስተዳድሩ',
    'assets.addNew': 'አዲስ ንብረት ይመዝግቡ',
    'assets.code': 'የንብረት ኮድ',
    'assets.name': 'ስም',
    'assets.category': 'ምድብ',
    'assets.assignedTo': 'የተመደበለት',
    'assets.purchaseDate': 'የግዢ ቀን',
    'posts.manage': 'ዜና ያስተዳድሩ',
    'posts.overview': 'የዜና መልዕክቶችን ይፍጠሩ እና ያስተዳድሩ',
    'posts.createNew': 'አዲስ መልዕክት ይፍጠሩ',
    'posts.title': 'ርዕስ',
    'posts.content': 'ይዘት',
    'posts.author': 'ደራሲ',
    'posts.date': 'ቀን',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
