import React, { createContext, useContext, useState } from "react";

type Language = "en" | "am" | "om";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.users": "Manage Users",
    "nav.assets": "Manage Assets",
    "nav.posts": "Post News",
    "nav.profile": "Update Profile",
    "nav.whatsNew": "What's New",
    "nav.addUser": "Add New User",
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.welcome": "Welcome to Sunday School Portal",
    "auth.logout": "Logout",
    "auth.welcomeDescription":
      "Welcome back to your spiritual community. Sign in to continue your journey.",
    "auth.emailPlaceholder": "your@email.com",
    "auth.passwordPlaceholder": "••••••••",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot Password?",
    "auth.signingIn": "Signing in...",
    "auth.noAccount": "Don't have an account?",
    "auth.demoCredentials": "Demo Credentials",
    "auth.adminAccess": "Admin Access",
    "auth.memberAccess": "Member Access",
    "auth.communityText": "Join our growing spiritual community",
    "auth.weeklySessions": "Weekly Sessions",
    "auth.satisfaction": "Satisfaction",
    "auth.support": "Support",
    "auth.loginError": "Invalid email or password. Please try again.",
    "common.save": "Save Changes",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.role": "Role",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "profile.title": "Update Profile",
    "profile.personal": "Personal Information",
    "profile.details": "Location & Background",
    "profile.account": "Change Password",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.phone": "Phone",
    "profile.aboutMe": "About Me",
    "profile.address": "Address",
    "profile.city": "City",
    "profile.country": "Country",
    "profile.occupation": "Occupation",
    "profile.education": "Education",
    "profile.sundaySchool": "Sunday School",
    "profile.responsibility": "Responsibility",
    "profile.avatar": "Profile Picture",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "dashboard.overview": "Overview of your Sunday School management system",
    "dashboard.totalUsers": "Total Users",
    "dashboard.totalAssets": "Total Assets",
    "dashboard.activePosts": "Active Posts",
    "dashboard.engagement": "Engagement Rate",
    "dashboard.recentActivity": "Recent Activity",
    "users.manage": "Manage Users",
    "users.viewManage": "View and manage all registered users",
    "users.searchPlaceholder": "Search users...",
    "users.user": "User",
    "users.viewDetails": "View Details",
    "assets.manage": "Manage Assets",
    "assets.overview": "Track and manage all church assets",
    "assets.addNew": "Register New Asset",
    "assets.code": "Asset Code",
    "assets.name": "Name",
    "assets.category": "Category",
    "assets.assignedTo": "Assigned To",
    "assets.purchaseDate": "Purchase Date",
    "posts.manage": "Post News",
    "posts.overview": "Create and manage news posts",
    "posts.createNew": "Create New Post",
    "posts.title": "Title",
    "posts.content": "Content",
    "posts.author": "Author",
    "posts.date": "Date",
    "dashboard.fromLastMonth": "from last month",
    "dashboard.viewAll": "View all",
    "dashboard.viewDetails": "View details",
    "dashboard.activityDetails": "Activity Details",
    "dashboard.action": "Action",
    "dashboard.time": "Time",
    "dashboard.user": "User",
    "dashboard.email": "Email",
    "dashboard.details": "Details",
    "dashboard.exportReport": "Export Report",
    "dashboard.exportDetails": "Export Details",
    "dashboard.close": "Close",
    "dashboard.newUserRegistered": "New user registered",
    "dashboard.assetUpdated": "Asset updated",
    "dashboard.newPostPublished": "New post published",
    "dashboard.completedRegistration":
      "Completed registration with all required information.",
    "dashboard.updatedAssetStatus": "Updated asset BK-001 status to Available.",
    "dashboard.publishedWelcomePost":
      'Published "Welcome to Sunday School Portal"',
    "dashboard.hoursAgo": "hours ago",
    "dashboard.daysAgo": "days ago",
    "nav.adminPortal": "Admin Portal",
    "auth.admin": "Administrator",
    "profile.updateInfo": "Edit your personal information",
    "auth.logoutDesc": "Log out from your account",
    "auth.lastLogin": "Last login",
  },
  am: {
    "nav.dashboard": "ዳሽቦርድ",
    "nav.users": "ተጠቃሚዎችን ያስተዳድሩ",
    "nav.assets": "ንብረቶችን ያስተዳድሩ",
    "nav.posts": "ዜና ያስተዳድሩ",
    "nav.profile": "መገለጫ አዘምን",
    "nav.whatsNew": "አዲስ ምንድን ነው",
    "nav.addUser": "አዲስ ተጠቃሚ ያክሉ",
    "auth.login": "ግባ",
    "auth.signup": "ተመዝገብ",
    "auth.email": "ኢሜይል",
    "auth.password": "የይለፍ ቃል",
    "auth.welcome": "ወደ የእሁድ ትምህርት ቤት ፖርታል እንኳን በደህና መጡ",
    "auth.logout": "ውጣ",
    "auth.welcomeDescription": "ወደ መንፈሳዊ ማህበረሰብዎ በደህና ተመለሱ። ጉዞዎን ለመቀጠል ይግቡ።",
    "auth.emailPlaceholder": "ኢሜይል@ምሳሌ.ኮም",
    "auth.passwordPlaceholder": "••••••••",
    "auth.rememberMe": "አስታውሰኝ",
    "auth.forgotPassword": "የይለፍ ቃል ረሳኽ?",
    "auth.signingIn": "በመግባት ላይ...",
    "auth.noAccount": "መለያ የሎትም?",
    "auth.demoCredentials": "የሙከራ መለያ",
    "auth.adminAccess": "የአስተዳዳሪ መዳረሻ",
    "auth.memberAccess": "የአባል መዳረሻ",
    "auth.communityText": "የምንዳብረውን መንፈሳዊ ማህበረሰብ ይቀላቀሉ",
    "auth.weeklySessions": "የሳምንት ክፍለ ጊዜያት",
    "auth.satisfaction": "ዕፅፊያ",
    "auth.support": "ድጋፍ",
    "auth.loginError": "ልክ ያልሆነ ኢሜይል ወይም የይለፍ ቃል። እባክዎ እንደገና ይሞክሩ።",
    "common.save": "ለውጦችን አስቀምጥ",
    "common.cancel": "ሰርዝ",
    "common.delete": "አጥፋ",
    "common.edit": "አርትዕ",
    "common.search": "ፈልግ",
    "common.actions": "እርምጃዎች",
    "common.status": "ሁኔታ",
    "common.role": "ሚና",
    "common.active": "ንቁ",
    "common.inactive": "ንቁ ያልሆነ",
    "profile.title": "መገለጫ አዘምን",
    "profile.personal": "የግል መረጃ",
    "profile.details": "አድራሻ እና ዳራ",
    "profile.account": "የይለፍ ቃል ቀይር",
    "profile.firstName": "ስም",
    "profile.lastName": "የአባት ስም",
    "profile.phone": "ስልክ",
    "profile.aboutMe": "ስለ እኔ",
    "profile.address": "አድራሻ",
    "profile.city": "ከተማ",
    "profile.country": "ሀገር",
    "profile.occupation": "ስራ",
    "profile.education": "ትምህርት",
    "profile.sundaySchool": "የእሁድ ትምህርት ቤት",
    "profile.responsibility": "ኃላፊነት",
    "profile.avatar": "የመገለጫ ምስል",
    "profile.currentPassword": "የአሁኑ የይለፍ ቃል",
    "profile.newPassword": "አዲስ የይለፍ ቃል",
    "profile.confirmPassword": "አዲስ የይለፍ ቃል ያረጋግጡ",
    "dashboard.overview": "የእሁድ ትምህርት ቤት አስተዳደር ስርዓት አጠቃላይ እይታ",
    "dashboard.totalUsers": "ጠቅላላ ተጠቃሚዎች",
    "dashboard.totalAssets": "ጠቅላላ ንብረቶች",
    "dashboard.activePosts": "ንቁ መልዕክቶች",
    "dashboard.engagement": "የተሳትፎ መጠን",
    "dashboard.recentActivity": "የቅርብ ጊዜ እንቅስቃሴ",
    "users.manage": "ተጠቃሚዎችን ያስተዳድሩ",
    "users.viewManage": "ሁሉንም የተመዘገቡ ተጠቃሚዎችን ይመልከቱ እና ያስተዳድሩ",
    "users.searchPlaceholder": "ተጠቃሚዎችን ፈልግ...",
    "users.user": "ተጠቃሚ",
    "users.viewDetails": "ዝርዝሮችን ይመልከቱ",
    "assets.manage": "ንብረቶችን ያስተዳድሩ",
    "assets.overview": "ሁሉንም የቤተክርስቲያን ንብረቶች ይከታተሉ እና ያስተዳድሩ",
    "assets.addNew": "አዲስ ንብረት ይመዝግቡ",
    "assets.code": "የንብረት ኮድ",
    "assets.name": "ስም",
    "assets.category": "ምድብ",
    "assets.assignedTo": "የተመደበለት",
    "assets.purchaseDate": "የግዢ ቀን",
    "posts.manage": "ዜና ያስተዳድሩ",
    "posts.overview": "የዜና መልዕክቶችን ይፍጠሩ እና ያስተዳድሩ",
    "posts.createNew": "አዲስ መልዕክት ይፍጠሩ",
    "posts.title": "ርዕስ",
    "posts.content": "ይዘት",
    "posts.author": "ደራሲ",
    "posts.date": "ቀን",
    "dashboard.fromLastMonth": "ከያዘው ወር",
    "dashboard.viewAll": "ሁሉንም ይመልከቱ",
    "dashboard.viewDetails": "ዝርዝሮችን ይመልከቱ",
    "dashboard.activityDetails": "የእንቅስቃሴ ዝርዝሮች",
    "dashboard.action": "ተግባር",
    "dashboard.time": "ጊዜ",
    "dashboard.user": "ተጠቃሚ",
    "dashboard.email": "ኢሜይል",
    "dashboard.details": "ዝርዝሮች",
    "dashboard.exportReport": "ሪፖርት ላክ",
    "dashboard.exportDetails": "ዝርዝሮችን ላክ",
    "dashboard.close": "ዝጋ",
    "dashboard.newUserRegistered": "አዲስ ተጠቃሚ ተመዝግቧል",
    "dashboard.assetUpdated": "ንብረት ዘምኗል",
    "dashboard.newPostPublished": "አዲስ ልጥፍ ተለቅቋል",
    "dashboard.completedRegistration": "ሁሉንም የሚያስፈልጉ መረጃዎች በመሙላት ምዝገባ ተጠናቅቋል።",
    "dashboard.updatedAssetStatus": "የ BK-001 ንብረት ሁኔታ ወደ የሚገኝ ተቀይሯል።",
    "dashboard.publishedWelcomePost":
      '"ወደ እሁድ ትምህርት ቤት ፖርታል እንኳን በደህና መጡ" ተለቅቋል',
    "dashboard.hoursAgo": "ሰዓታት በፊት",
    "dashboard.daysAgo": "ቀናት በፊት",
    "nav.adminPortal": "የአስተዳዳሪ ፖርታል",
    "auth.admin": "አስተዳዳሪ",
    "profile.updateInfo": "የግል መረጃዎትን ያርትዑ",
    "auth.logoutDesc": "ከመለያዎ ይውጡ",
    "auth.lastLogin": "የመጨረሻ ግባ",
  },
  om: {
    "nav.dashboard": "Daashboorduu",
    "nav.users": "Fayyadamaawwan Gargaaru",
    "nav.assets": "Qabeenyaawwan Gargaaru",
    "nav.posts": "Oduu Dhiheessuu",
    "nav.profile": "Pirofaayilii Haaraa",
    "nav.whatsNew": "Waan Haaraa Maali?",
    "nav.addUser": "Fayyadamaa Haaraa Dabalatu",
    "auth.login": "Seenuu",
    "auth.signup": "Galmeeffachuu",
    "auth.email": "Imeelii",
    "auth.password": "Jecha Iccitiin",
    "auth.welcome": "Baga Portal Mana Barumsa Jirmaa Geessan",
    "auth.logout": "Ba'i",
    "auth.welcomeDescription":
      "Haala hawaasaa keessan seenuu dhiisee deebi'aa. Imalaa keessan itti fufuuf seenaa.",
    "auth.emailPlaceholder": "imeelii@fake.com",
    "auth.passwordPlaceholder": "••••••••",
    "auth.rememberMe": "Na yaadadhu",
    "auth.forgotPassword": "Jecha icciitii irraanfatte?",
    "auth.signingIn": "Seenuu keessatti...",
    "auth.noAccount": "Akkaawuntii hin qabduu?",
    "auth.demoCredentials": "Mallattoo yaalaa",
    "auth.adminAccess": "Dhaabbata Misoomaa",
    "auth.memberAccess": "Dhaabbata Dhaabbataa",
    "auth.communityText": "Hawaasa keenya guddataa ta'ee walii galuu",
    "auth.weeklySessions": "Turtii Torbanii",
    "auth.satisfaction": "Qancara",
    "auth.support": "Gargaarsa",
    "auth.loginError":
      "Imeelii ykn jecha icciitii dogoggora. Mee irra deebi'ii yaalaa.",
    "common.save": "Jijjiiramaawwan Tiksuu",
    "common.cancel": "Haqi",
    "common.delete": "Haaluu",
    "common.edit": "Gulaaluu",
    "common.search": "Barbaadi",
    "common.actions": "Hojiiwwan",
    "common.status": "Haala",
    "common.role": "Dhuunfa",
    "common.active": "Hojii irra jira",
    "common.inactive": "Hojii irra hin jirre",
    "profile.title": "Pirofaayilii Haaraa",
    "profile.personal": "Odeeffannoo Dhuunfaa",
    "profile.details": "Teessoo & Duubaa",
    "profile.account": "Jecha Iccitiin Jijjiiraa",
    "profile.firstName": "Maqaa Dhuunfaa",
    "profile.lastName": "Maqaa Maatii",
    "profile.phone": "Bilbila",
    "profile.aboutMe": "Waa'ee Koo",
    "profile.address": "Teessoo",
    "profile.city": "Magaalaa",
    "profile.country": "BiYYaa",
    "profile.occupation": "Hojii",
    "profile.education": "Barumsa",
    "profile.sundaySchool": "Mana Barumsa Jirmaa",
    "profile.responsibility": "Dhimma",
    "profile.avatar": "Suura Pirofaayilii",
    "profile.currentPassword": "Jecha Iccitiin Ammaa",
    "profile.newPassword": "Jecha Iccitiin Haaraa",
    "profile.confirmPassword": "Jecha Iccitiin Haaraa Mirkaneessi",
    "dashboard.overview": "Daa'imman mana barumsa jirmaa waliigalaa",
    "dashboard.totalUsers": "Waliigala Fayyadamaawwan",
    "dashboard.totalAssets": "Waliigala Qabeenyaawwan",
    "dashboard.activePosts": "Odeeffannoo Hojii irra jiran",
    "dashboard.engagement": "Sadarkaa Qooda Fudhannoo",
    "dashboard.recentActivity": "Hojiin Dhihoo",
    "users.manage": "Fayyadamaawwan Gargaaru",
    "users.viewManage": "Fayyadamaawwan galmeeffaman hunda ilaaliifi gargaaru",
    "users.searchPlaceholder": "Fayyadamaawwan barbaadi...",
    "users.user": "Fayyadamtuu",
    "users.viewDetails": "Faankishinoota Ilaali",
    "assets.manage": "Qabeenyaawwan Gargaaru",
    "assets.overview": "Qabeenyaawwan mana nagaaas hunda hordofifi gargaaru",
    "assets.addNew": "Qabeenyi Haaraa Galmeessi",
    "assets.code": "Koodii Qabeenyaa",
    "assets.name": "Maqaa",
    "assets.category": "Garee",
    "assets.assignedTo": "Kenname",
    "assets.purchaseDate": "Guyyaa Bittaa",
    "posts.manage": "Oduu Dhiheessuu",
    "posts.overview": "Oduu uumuu fi gargaaruu",
    "posts.createNew": "Oduu Haaraa Uumuu",
    "posts.title": "Mata Duree",
    "posts.content": "Qabxii",
    "posts.author": "Barreessaa",
    "posts.date": "Guyyaa",
    "dashboard.fromLastMonth": "ji'a darbee irraa",
    "dashboard.viewAll": "Hunda ilaali",
    "dashboard.viewDetails": "Faankishinoota ilaali",
    "dashboard.activityDetails": "Faankishinoota Hojiia",
    "dashboard.action": "Hojii",
    "dashboard.time": "Yeroo",
    "dashboard.user": "Fayyadamtuu",
    "dashboard.email": "Imeelii",
    "dashboard.details": "Faankishinoota",
    "dashboard.exportReport": "Ripoortii Ergaa",
    "dashboard.exportDetails": "Faankishinoota Ergaa",
    "dashboard.close": "Cufi",
    "dashboard.newUserRegistered": "Fayyadamtuu haaraa galmeeffame",
    "dashboard.assetUpdated": "Qabeenyi haaromsame",
    "dashboard.newPostPublished": "Oduu haaraa maxxanfame",
    "dashboard.completedRegistration":
      "Galmeeffannoo oodeeffannoo barbaachisaa hunda guutuu xumurate.",
    "dashboard.updatedAssetStatus":
      "Haala qabeenyaa BK-001 jiraachuu dhaan haaromsame.",
    "dashboard.publishedWelcomePost":
      '"Baga Portal Mana Barumsa Jirmaa Geessan" maxxanfame',
    "dashboard.hoursAgo": "saatii dura",
    "dashboard.daysAgo": "guyyoo dura",
    "nav.adminPortal": "Portaala Misoomaa",
    "auth.admin": "Misoomaa",
    "profile.updateInfo": "Odeeffannoo dhuunfaa kee gulaali",
    "auth.logoutDesc": "Akkaawuntii kee irraa ba'i",
    "auth.lastLogin": "Seenuu dhumaa",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
